package banco1;

/**
* banco1/BancoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banco1.idl
* miércoles 22 de abril de 2015 19H43' CDT
*/

public final class BancoHolder implements org.omg.CORBA.portable.Streamable
{
  public banco1.Banco value = null;

  public BancoHolder ()
  {
  }

  public BancoHolder (banco1.Banco initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banco1.BancoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banco1.BancoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banco1.BancoHelper.type ();
  }

}
