package banco1;


/**
* banco1/BancoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banco1.idl
* miércoles 22 de abril de 2015 19H43' CDT
*/

public interface BancoOperations 
{
  void crearCuenta (banco1.Datos datos);
  double depositar (int numero, double cantidad);
  double retirar (int numero, double cantidad);
  double consulta (int num);
  banco1.Datos[] verCuentas ();
} // interface BancoOperations
