package banco1;


/**
* banco1/DatosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banco1.idl
* miércoles 22 de abril de 2015 19H43' CDT
*/

public abstract class DatosPOA extends org.omg.PortableServer.Servant
 implements banco1.DatosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setNumCuenta", new java.lang.Integer (0));
    _methods.put ("setSaldo", new java.lang.Integer (1));
    _methods.put ("setNombre", new java.lang.Integer (2));
    _methods.put ("getNombre", new java.lang.Integer (3));
    _methods.put ("getNumCuenta", new java.lang.Integer (4));
    _methods.put ("getSaldo", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // banco1/Datos/setNumCuenta
       {
         int numC = in.read_long ();
         this.setNumCuenta (numC);
         out = $rh.createReply();
         break;
       }

       case 1:  // banco1/Datos/setSaldo
       {
         double cantidad = in.read_double ();
         this.setSaldo (cantidad);
         out = $rh.createReply();
         break;
       }

       case 2:  // banco1/Datos/setNombre
       {
         String nombre = in.read_string ();
         this.setNombre (nombre);
         out = $rh.createReply();
         break;
       }

       case 3:  // banco1/Datos/getNombre
       {
         String $result = null;
         $result = this.getNombre ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // banco1/Datos/getNumCuenta
       {
         int $result = (int)0;
         $result = this.getNumCuenta ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // banco1/Datos/getSaldo
       {
         double $result = (double)0;
         $result = this.getSaldo ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:banco1/Datos:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Datos _this() 
  {
    return DatosHelper.narrow(
    super._this_object());
  }

  public Datos _this(org.omg.CORBA.ORB orb) 
  {
    return DatosHelper.narrow(
    super._this_object(orb));
  }


} // class DatosPOA
