package banco1;

/**
* banco1/DatosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banco1.idl
* miércoles 22 de abril de 2015 19H43' CDT
*/

public final class DatosHolder implements org.omg.CORBA.portable.Streamable
{
  public banco1.Datos value = null;

  public DatosHolder ()
  {
  }

  public DatosHolder (banco1.Datos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banco1.DatosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banco1.DatosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banco1.DatosHelper.type ();
  }

}
