package banco1;


/**
* banco1/sequenceDatosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banco1.idl
* miércoles 22 de abril de 2015 19H43' CDT
*/

abstract public class sequenceDatosHelper
{
  private static String  _id = "IDL:banco1/sequenceDatos:1.0";

  public static void insert (org.omg.CORBA.Any a, banco1.Datos[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static banco1.Datos[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = banco1.DatosHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (banco1.sequenceDatosHelper.id (), "sequenceDatos", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static banco1.Datos[] read (org.omg.CORBA.portable.InputStream istream)
  {
    banco1.Datos value[] = null;
    int _len0 = istream.read_long ();
    value = new banco1.Datos[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = banco1.DatosHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, banco1.Datos[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      banco1.DatosHelper.write (ostream, value[_i0]);
  }

}
